In [1]:
import pandas as pd
# 載入Google股價的訓練資料集
df_train = pd.read_csv("Intel_dataset_train.csv", index_col="Date",parse_dates=True)
print(df_train.head())

            Open       High        Low      Close  Adj Close    Volume    SOX  \
Date                                                                            
42006  36.669998  37.160000  36.110001  36.360001  28.270075  23605600  686.7   
42009  36.200001  36.450001  35.939999  35.950001  27.951288  32785000  673.6   
42010  36.080002  36.230000  35.259998  35.279999  27.430363  30847600  658.8   
42011  35.639999  36.070000  35.270000  36.020000  28.005720  27725200  665.3   
42012  36.369999  37.000000  36.259998  36.689999  28.526644  31765400  684.6   

        COMEX  OilFut  Volatility  USDINDEX  
Date                                         
42006  1186.2   52.69       17.79     91.08  
42009  1204.0   50.04       19.92     91.38  
42010  1219.4   47.93       21.12     91.50  
42011  1210.7   48.65       19.31     91.89  
42012  1208.5   48.79       17.01     92.37  


In [2]:
# 讀取訓練資料
df_train = pd.read_csv("Intel_dataset_train.csv",index_col="Date",parse_dates=True)
# 倒數第二格是希望模型預測的結果，因此指定為倒數第二格的修正後收盤價
X_train_set = df_train.drop(labels = ['Adj Close'],axis=1).values
Y_train_set = df_train['Adj Close'].values
print(X_train_set.shape)
# 計算總共有幾筆
X_train_len = len(X_train_set)
print("筆數: ", X_train_len)

(2014, 10)
筆數:  2014


In [3]:
print(X_train_set[0])
print(Y_train_set[0])
print(X_train_set.shape)
print(Y_train_set.shape)

[3.6669998e+01 3.7160000e+01 3.6110001e+01 3.6360001e+01 2.3605600e+07
 6.8670000e+02 1.1862000e+03 5.2690000e+01 1.7790000e+01 9.1080000e+01]
28.270075
(2014, 10)
(2014,)


In [3]:
import numpy as np

# 產生特徵資料和標籤資料，預設look_back是一天，如果有給資料則更多
def create_dataset(ds, look_back=1):
    X_data, Y_data = [],[]
    # 每筆訓練資料有 look_back 天的參考資料，標籤為當天的修正後收盤價
    # 第 x 天價格的訓練資料需要有 x-1, x-2, x-3 ...... 到 x-look_back 天
    for i in range(len(ds)-look_back):
        X_data.append(ds[i:(i+look_back), :])
        Y_data.append(ds[i+look_back, :])
    return np.array(X_data), np.array(Y_data)

def create_dataset_forY(ds, look_back=1):
    X_data, Y_data = [],[]
    # 每筆訓練資料有 look_back 天的參考資料，標籤為當天的修正後收盤價
    # 第 x 天價格的訓練資料需要有 x-1, x-2, x-3 ...... 到 x-look_back 天
    for i in range(len(ds)-look_back):
        X_data.append(ds[i:(i+look_back), :])
        Y_data.append(ds[i+look_back, :])
    return np.array(X_data), np.array(Y_data)


# 這邊設定回看5天
look_back = 5

X_train,X_drop = create_dataset(X_train_set, look_back)
Y_train = Y_train_set[5:]
print("回看天數:", look_back)
print("X_train Shape: ", X_train.shape)
print("Y_train Shape: ", Y_train.shape)
print(X_train_set)
print(X_train.shape)
print(Y_train.shape)

回看天數: 5
X_train Shape:  (2009, 5, 10)
Y_train Shape:  (2009,)
[[ 36.669998  37.16      36.110001 ...  52.69      17.79      91.08    ]
 [ 36.200001  36.450001  35.939999 ...  50.04      19.92      91.38    ]
 [ 36.080002  36.23      35.259998 ...  47.93      21.12      91.5     ]
 ...
 [ 25.84      26.120001  25.5      ...  78.6       22.14     104.46    ]
 [ 25.77      26.290001  25.75     ...  78.61      21.44     103.84    ]
 [ 25.9       26.459999  25.799999 ...  80.47      21.67     103.52    ]]
(2009, 5, 10)
(2009,)


In [4]:
# 每筆資料六十筆
print(X_train.shape)

(2009, 5, 10)


In [5]:
print(Y_train)

[28.581068 28.456675 28.37892  ... 24.957489 25.612206 25.827187]


In [6]:
from sklearn.preprocessing import MinMaxScaler
print(X_train_set)
print("==============")
print(Y_train)
# 特徵標準化 - 正規化
sc = MinMaxScaler()
X_train_set = sc.fit_transform(X_train_set)
print("==============")
print(X_train_set)
print("==============")
print(Y_train)

C:\Users\WMNL\anaconda3\lib\site-packages\scipy\__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.26.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


[[ 36.669998  37.16      36.110001 ...  52.69      17.79      91.08    ]
 [ 36.200001  36.450001  35.939999 ...  50.04      19.92      91.38    ]
 [ 36.080002  36.23      35.259998 ...  47.93      21.12      91.5     ]
 ...
 [ 25.84      26.120001  25.5      ...  78.6       22.14     104.46    ]
 [ 25.77      26.290001  25.75     ...  78.61      21.44     103.84    ]
 [ 25.9       26.459999  25.799999 ...  80.47      21.67     103.52    ]]
[28.581068 28.456675 28.37892  ... 24.957489 25.612206 25.827187]
[[0.27467216 0.26660579 0.26966296 ... 0.55984628 0.11760707 0.09757053]
 [0.26386017 0.25039947 0.26568351 ... 0.54342032 0.14656696 0.10932602]
 [0.26109967 0.24537776 0.24976588 ... 0.53034154 0.16288239 0.11402821]
 ...
 [0.02553485 0.01460856 0.0213015  ... 0.72044877 0.17675051 0.6218652 ]
 [0.02392455 0.01848895 0.02715356 ... 0.72051075 0.16723317 0.59757053]
 [0.02691512 0.0223693  0.02832395 ... 0.73203992 0.1703603  0.58503135]]
[28.581068 28.456675 28.37892  ... 24.957489 2

In [7]:
# 分割成特徵資料和標籤資料
X_train= create_dataset(X_train_set, look_back)
print(X_train)


(array([[[0.27467216, 0.26660579, 0.26966296, ..., 0.55984628,
         0.11760707, 0.09757053],
        [0.26386017, 0.25039947, 0.26568351, ..., 0.54342032,
         0.14656696, 0.10932602],
        [0.26109967, 0.24537776, 0.24976588, ..., 0.53034154,
         0.16288239, 0.11402821],
        [0.25097768, 0.24172563, 0.25000001, ..., 0.53480444,
         0.13827328, 0.12931034],
        [0.26777087, 0.26295366, 0.27317412, ..., 0.53567222,
         0.10700204, 0.14811912]],

       [[0.26386017, 0.25039947, 0.26568351, ..., 0.54342032,
         0.14656696, 0.10932602],
        [0.26109967, 0.24537776, 0.24976588, ..., 0.53034154,
         0.16288239, 0.11402821],
        [0.25097768, 0.24172563, 0.25000001, ..., 0.53480444,
         0.13827328, 0.12931034],
        [0.26777087, 0.26295366, 0.27317412, ..., 0.53567222,
         0.10700204, 0.14811912],
        [0.27697264, 0.26546452, 0.27645137, ..., 0.53300688,
         0.11434398, 0.13126959]],

       [[0.26109967, 0.24537776, 0.

In [8]:
print(X_train[0])
print(Y_train[0])

[[[0.27467216 0.26660579 0.26966296 ... 0.55984628 0.11760707 0.09757053]
  [0.26386017 0.25039947 0.26568351 ... 0.54342032 0.14656696 0.10932602]
  [0.26109967 0.24537776 0.24976588 ... 0.53034154 0.16288239 0.11402821]
  [0.25097768 0.24172563 0.25000001 ... 0.53480444 0.13827328 0.12931034]
  [0.26777087 0.26295366 0.27317412 ... 0.53567222 0.10700204 0.14811912]]

 [[0.26386017 0.25039947 0.26568351 ... 0.54342032 0.14656696 0.10932602]
  [0.26109967 0.24537776 0.24976588 ... 0.53034154 0.16288239 0.11402821]
  [0.25097768 0.24172563 0.25000001 ... 0.53480444 0.13827328 0.12931034]
  [0.26777087 0.26295366 0.27317412 ... 0.53567222 0.10700204 0.14811912]
  [0.27697264 0.26546452 0.27645137 ... 0.53300688 0.11434398 0.13126959]]

 [[0.26109967 0.24537776 0.24976588 ... 0.53034154 0.16288239 0.11402821]
  [0.25097768 0.24172563 0.25000001 ... 0.53480444 0.13827328 0.12931034]
  [0.26777087 0.26295366 0.27317412 ... 0.53567222 0.10700204 0.14811912]
  [0.27697264 0.26546452 0.2764513

In [9]:
print(X_train.shape)
print(Y_train.shape)

AttributeError: 'tuple' object has no attribute 'shape'

In [13]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, SimpleRNN

# 定義模型
model = Sequential()
model.add(SimpleRNN(50, return_sequences=True,
               input_shape=(X_train.shape[1], 1)))
model.add(Dropout(0.2))
model.add(SimpleRNN(50, return_sequences=True))
model.add(Dropout(0.2))
model.add(SimpleRNN(50))
model.add(Dropout(0.2))
model.add(Dense(1))
model.summary()   # 顯示模型摘要資訊

AttributeError: 'tuple' object has no attribute 'shape'

In [ ]:
Y_train

In [ ]:
# 編譯模型
model.compile(loss="mse", optimizer="adam")
# 訓練模型
model.fit(X_train, Y_train, epochs=50, batch_size=32)

In [ ]:
# 使用模型預測股價 - 2022年1~3月預測 4 月份股價
df_test = pd.read_csv("Intel_dataset_test.csv",index_col="Date",parse_dates=True)
X_test_set = df_test.drop(labels = ['Adj Close'],axis=1).values     # 刪除adj close
# 產生特徵資料和標籤資料
X_test_set = sc.transform(X_test_set)
X_test, Y_test = create_dataset(X_test_set, look_back)
print(X_test)
print(Y_test)
print(X_test.shape)
print(Y_test.shape)

In [11]:
# 轉換成(樣本數, 時步, 特徵)張量
X_test = np.reshape(X_test, (X_test.shape[0], X_test.shape[1], 10))
print(X_test.shape)
X_test_pred = model.predict(X_test)
print(X_test_pred.shape)

NameError: name 'X_test' is not defined

In [12]:
print(X_test_pred.shape)
print(Y_test.shape)

NameError: name 'X_test_pred' is not defined

In [25]:
X_test_pred_price = sc2.inverse_transform(X_test_pred)
print(X_test_pred_price)

ValueError: non-broadcastable output operand with shape (212,1) doesn't match the broadcast shape (212,10)

In [ ]:
Y_test = Y_test.reshape(212,1)
Y_test = sc.inverse_transform(Y_test)
print(Y_test)

In [ ]:
# 繪出股價圖表
import matplotlib.pyplot as plt

plt.plot(Y_test, color="red", label="Real Stock Price")
plt.plot(X_test_pred_price, color="blue", label="Predicted Stock Price")
plt.title("2023 Intel Corporation Stock Price Prediction")
plt.xlabel("Time")
plt.ylabel("Intel Time Price")
plt.legend()
plt.show()

In [ ]:
# 倒數第二格是希望模型預測的結果，因此把一般的收盤價 close 去除
df2 = df_train
df2 = df2.drop(columns=['Close'])

# 把因為處理的方便性，因此我要調換一下順續
# 先拿到 column list
cols = df2.columns.to_list()
# 交換 column 順序
cols = cols[5:11] + cols[:3] + cols[4:5] + cols[3:4]
# 套用新的 column 順序
df2 = df2[cols]

# 調換順序後的df2
df2

In [ ]:
# 因為這邊參照資料有5個欄位，而預測出來的資料只有一個值，因此這邊我們必須採用兩個等化器

sc1 = MinMaxScaler()
sc2 = MinMaxScaler()
# 將帶有逗號的字符串轉換為浮點數
# columns_to_scale = ['Open', 'High', 'Low', 'Volume', 'SOX', 'COMEX', 'OilFut', 'Volatility', 'USDINDEX', 'Adj Close']

# for column in columns_to_scale:
#     if df2[column].dtype == 'O':  # 檢查是否為對象(字符串)類型
#         df2[column] = df2[column].str.replace(',', '').astype(float)
#     else:
#         # 如果列已經是數字類型，則無需轉換
#         continue

# 現在應用 MinMaxScaler
df2[['Open', 'High', 'Low', 'Volume', 'SOX', 'COMEX', 'OilFut', 'Volatility', 'USDINDEX']] = sc1.fit_transform(df2[['Open', 'High', 'Low', 'Volume', 'SOX', 'COMEX', 'OilFut', 'Volatility', 'USDINDEX']])
df2[['Adj Close']] = sc2.fit_transform(df2[['Adj Close']])

In [ ]:
X_train_set = df2.drop(['Adj Close'],axis=1).values

#X_train_set = df2.iloc[:,0:5].values

# 產生特徵資料和標籤資料
print(X_train_set)

In [ ]:
# 取出幾天前股價來建立成特徵和標籤資料集
def create_dataset(ds, look_back=1):
    X_data, Y_data = [],[]
    for i in range(len(ds)-look_back):
        X_data.append(ds[i:(i+look_back), 0:5])
        Y_data.append(ds[i+look_back, 4:5])

    return np.array(X_data), np.array(Y_data)

# 分割成特徵資料和標籤資料
X_train, Y_train = create_dataset(X_train_set, look_back)

In [ ]:
X_train.shape

In [ ]:
print(X_train)

In [ ]:
# 定義模型
model = Sequential()
model.add(SimpleRNN(50, return_sequences=True,
               input_shape=(X_train.shape[1], 5)))
model.add(Dropout(0.2))
model.add(SimpleRNN(50, return_sequences=True))
model.add(Dropout(0.2))
model.add(SimpleRNN(50))
model.add(Dropout(0.2))
model.add(Dense(1))
model.summary()   # 顯示模型摘要資訊

In [ ]:
# 編譯模型
model.compile(loss="mse", optimizer="adam")
# 訓練模型
model.fit(X_train, Y_train, epochs=50, batch_size=32)

In [ ]:
print(X_train)

In [ ]:
# 使用模型預測股價 - 2022年1~3月預測 4 月份股價
df_test = pd.read_csv("Intel_dataset_test.csv", index_col="Date",parse_dates=True)

df2 = df_test
df2 = df2.drop(columns=['Close'])

In [ ]:
df2

In [ ]:
# 把因為處理的方便性，因此我要調換一下順續
# 先拿到 column list
cols = df2.columns.to_list()
# 交換 column 順序
cols = cols[:3] + cols[4:5] + cols[3:4] + cols[5:11]
# 套用新的 column 順序
df2 = df2[cols]

# 調換順序後的df2
df2

In [ ]:

# 等化器要用同一組
df2[['Open', 'High', 'Low', 'Volume','SOX','COMEX','OilFut','Volatility','USDINDEX']] = sc1.transform(df2[['Open', 'High', 'Low', 'Volume','SOX','COMEX','OilFut','Volatility','USDINDEX']])
df2[['Adj Close']] = sc2.transform(df2[['Adj Close']])
df2

In [ ]:
X_test_set = df2.iloc[:,0:5].drop('Adj Close', axis=1).value
X_test, Y_test = create_dataset(X_test_set, look_back)

In [ ]:
# 預測出來的結果
X_test_pred = model.predict(X_test)
print(X_test_pred)

In [ ]:
# 將預測值轉換回股價
X_test_pred_price = sc2.inverse_transform(X_test_pred)
print(X_test_pred_price)

In [ ]:
Y_test = Y_test.reshape(212,1)
Y_test = sc.inverse_transform(Y_test)
print(Y_test)

In [ ]:
# 繪出股價圖表
import matplotlib.pyplot as plt

plt.plot(Y_test, color="red", label="Real Stock Price")
plt.plot(X_test_pred_price, color="blue", label="Predicted Stock Price")
plt.title("2023 Intel Corporation Stock Price Prediction")
plt.xlabel("Time")
plt.ylabel("Intel Time Price")
plt.legend()
plt.show()